// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.FullJS.Sections.Section2 = (function(_super) {

    __extends(Section2, _super);

    function Section2() {
      this.init = __bind(this.init, this);
      return Section2.__super__.constructor.apply(this, arguments);
    }

    Section2.prototype.init = function() {
      this.container.css({
        overflow: "hidden"
      });
      this.item1 = this.createItem({
        width: 100,
        height: 100,
        backgroundColor: "#FFFFFF",
        position: "absolute"
      });
      return this.item2 = this.createItem({
        width: 100,
        height: 100,
        backgroundColor: "#FFFFFF",
        position: "absolute"
      });
    };

    Section2.prototype.update = function(absolute, relative, ratio, width, height) {
      var size;
      ratio += 0.2;
      size = ratio < 0 ? 0 : ratio * 100;
      this.container.css({
        opacity: 1 - relative / (this.inVector === 1 ? -this.preOffset : this.postOffset)
      });
      this.item1.css({
        top: relative * 1.2,
        right: relative * 0.4 + 200,
        width: size,
        height: size
      });
      return this.item2.css({
        top: relative * 0.4 + 200,
        right: relative * 1.2 + 200
      });
    };

    return Section2;

  })(this.FullJS.Sections.Base);

}).call(this);
