// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.FullJS.Sections.Section2 = (function(_super) {

    __extends(Section2, _super);

    function Section2() {
      this.update = __bind(this.update, this);

      this.init = __bind(this.init, this);
      return Section2.__super__.constructor.apply(this, arguments);
    }

    Section2.prototype.init = function() {
      this.container.css({
        overflow: "hidden"
      });
      this.autoPostOffsetRatio = 10;
      this.item1 = this.createItem({
        position: "absolute"
      }, '<img src="images/s.png" />');
      this.item2 = this.createItem({
        position: "absolute"
      }, '<img src="images/b.png" />');
      return this.item3 = this.createItem({
        position: "absolute"
      }, '<img src="images/k.png" />');
    };

    Section2.prototype.update = function(absolute, relative, ratio, width, height) {
      var hh, rr, wh;
      if (relative > 0) {
        this.container.css({
          top: 0,
          backgroundPosition: "0 " + (relative % 16) + "px"
        });
      }
      wh = width >> 1;
      hh = height >> 1;
      rr = 1 - ratio;
      this.item1.css({
        left: ratio * -500 + (wh - 600),
        top: ratio * 500 + (hh - 300)
      });
      this.item2.css({
        left: rr * (wh - 250),
        top: rr * (hh - 200)
      });
      return this.item3.css({
        left: rr * (wh + 40),
        top: rr * (hh - 500)
      });
    };

    return Section2;

  })(this.FullJS.Sections.Base);

}).call(this);
