// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.FullJS.Sections.Example = (function(_super) {

    __extends(Example, _super);

    function Example() {
      this.update = __bind(this.update, this);

      this.init = __bind(this.init, this);
      return Example.__super__.constructor.apply(this, arguments);
    }

    Example.prototype.init = function() {
      /* 初期化
      */

    };

    Example.prototype.update = function(absolute, relative, ratio, width, height, inVector) {
      /* アニメーションなど
      */

    };

    return Example;

  })(this.FullJS.Sections.Base);

}).call(this);
